# config/config.yaml

watcher:
  watch_folder: "backend/audio"
  file_extension: ".wav"

transcriber:
  model_size: "base"
  transcripts_dir: "backend/transcripts"

pitch:
  output_dir: "backend/output/pitch"
