name: Python CI

nn:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
         python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }-|pip-${{ hashFiles('Bakend/requirements.txt' )}}
          restore-keys: |
            ${ runner.os }-pip-

    - name: Install dependencies
       run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install pytest pytest-cov

    - name: Run tests with coverage
       run: |
        cd backend
        pytest --cov=modules --cov-report=xml --cov-fail-under=70

    - name: Upload coverage to Codecov 
      uses: codecov/codecov-action@v4
      with:
        files: backend/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Archive test results (always)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: backend/.pytest_cache/
