name: Python CI

nn:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Cache pip
        use: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${ runner.os }-pip-${ hashFiles('backend/requirements.txt') }
          restore-keys: |
            ${ runner.os }-pip-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip sync -r backend/requirements.txt
          pip install pytest
      - name: Run tests via entrypoint
        run: python run_tests.py
      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v4
        with:
          files: backend/coverage.xml
          token: ${ ${secrets.CODECOV_TOKEN }}
      - name: Archive test results (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: backend/.pytest_cache/
